#5 코드 리팩토링 입니다
SEO-J17/RandomPictureViewer pull request #7
Opened 2022-10-29 08:56 UTC by SEO-J17

기억을 더듬어 최대한 리팩토링 했습니다..
DetailActivity 쪽이 조금 미비한 것 같습니다ㅜㅜ

2022-10-29 15:46 UTC, f-lab-mark commented
.idea 폴더에 있는 내용은 git에 포함 되면 안됩니다
gitignore를 수정해 주세요

2022-10-29 15:54 UTC, f-lab-mark requested changes

2022-10-29 15:54 UTC, f-lab-mark commented on app/src/main/java/project/seo/pictureviewer/DetailActivity.kt
> +    }
메서드 네임과 내용이 적절하지 않습니다

2022-10-29 15:54 UTC, f-lab-mark commented on app/src/main/java/project/seo/pictureviewer/DetailActivity.kt
> +            with(it) {
`with`로 묶는 값을 다르게 하는것을 권장합니다

2022-10-29 15:54 UTC, f-lab-mark commented on app/src/main/java/project/seo/pictureviewer/ListAdapter.kt
> +        }
`viewType` 작업을 따로 하지 않기 때문에 나눌필요가 없습니다

2022-10-29 15:54 UTC, f-lab-mark commented on app/src/main/java/project/seo/pictureviewer/ListViewHolder.kt
> +        }
코드 정렬이 이상합니다

2022-10-29 15:54 UTC, f-lab-mark commented on app/src/main/java/project/seo/pictureviewer/MainActivity.kt
> +        }
코드 정렬이 이상합니다

2022-10-29 15:54 UTC, f-lab-mark commented on app/src/main/java/project/seo/pictureviewer/MainActivity.kt
> +                            QueryUtils.extractData(response.body()))
코드 정렬이 이상합니다

2022-10-29 15:54 UTC, f-lab-mark commented on app/src/main/java/project/seo/pictureviewer/QueryUtils.kt
>      fun extractData(pictureData: PictureInfo?): MutableList<PictureData> {
`MutableList`로 필요로 하는지 다시한번 고민해보세요

2022-10-29 15:54 UTC, f-lab-mark commented on app/src/main/java/project/seo/pictureviewer/data/PictureData.kt
> +    val download_url: String,
네이밍이 안맞습니다

2022-10-29 15:54 UTC, f-lab-mark commented on app/src/main/java/project/seo/pictureviewer/network/RetrofitService.kt
> +        Retrofit.Builder().baseUrl(requestUrl)
코드 정렬이 안맞습니다

2022-10-29 17:00 UTC, SEO-J17 commented on app/src/main/java/project/seo/pictureviewer/DetailActivity.kt
> +            with(it) {
묶는 값을 binding으로 수정했습니다..! binding으로 묶는 것이 맞다면 binding으로 with하는 이유가 있을까요..?

2022-11-01 13:50 UTC, f-lab-mark approved these changes

2022-11-01 13:56 UTC, merged